version: "3.8"
services:
  udunu-app:
    image: ivangabriele/tauri:debian-bullseye-18
    container_name: udunu_app_container
    volumes:
      - .:/app
    environment:
      - NODE_ENV={NODE_ENV}
    ports:
      - "1420:1420"
